name: Build Packer Image

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_DB: ${{ secrets.DBNAME }}
        ports:
          - 5432:5432

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: "create environment varible"
      run: |
        touch .env
        echo DBNAME=${{ secrets.DBNAME}} >> .env
        echo USERNAME=${{ secrets.USERNAME }} >> .env
        echo PASSWORD=${{ secrets.PASSWORD }} >> .env

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Environment Variables
      run: |
        touch .env
        echo "HOST=${{ secrets.HOST }}" >> .env
        echo "DBNAME=${{ secrets.DBNAME }}" >> .env
        echo "USERNAME=${{ secrets.USERNAME }}" >> .env
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
    
    - name: Create Repository Zip with .env
      run: zip -r webapp.zip .env *

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Setup Packer Gcloud Plugin'
      run: 'packer plugins install github.com/hashicorp/googlecompute'
    
    - name: Packer Init
      run: packer init ./packer/gcp.pkr.hcl

    - name: Run Packer Build
      run: |
        packer build -var 'project_id='${{ secrets.GCP_PROJECT_NAME }} packer/gcp.pkr.hcl
