name: Build Packer Image

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Upload Repository Zip
      uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: webapp.zip

    - name: Download Repository Zip
      uses: actions/download-artifact@v2
      with:
        name: webapp

    - name: Setup Environment Variables
      run: |
        touch webapp/.env
        echo "HOST=${{ secrets.HOST }}" >> webapp/.env
        echo "DBNAME=${{ secrets.DBNAME }}" >> webapp/.env
        echo "USERNAME=${{ secrets.USERNAME }}" >> webapp/.env
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> webapp/.env
    
    - name: Create Repository Zip with .env
      run: zip -r webapp.zip .env *

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Run Packer Build
      run: |
        packer build -var 'project_id='${{ secrets.GCP_PROJECT_NAME }} packer/gcp.pkr.hcl
