name: Packer Checks

on: 
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  packer:
    name: Validate Packer Configuration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Packer Init
      run: packer init ./packer/gcp.pkr.hcl
      
    - name: Packer Validate
      run: packer validate ./packer/gcp.pkr.hcl
    
    - name: Run packer fmt
      run: |
        if ! packer fmt -check ./packer/gcp.pkr.hcl; then
        echo "Failed - Packer fmt"
        exit 1
        fi
