# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: testing

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    environment: ${{ vars.ENVIRONMENT }}
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ vars.DBNAME }}
          POSTGRES_USER: ${{ vars.USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    name: Run unit tests
    steps:
      - uses: actions/checkout@v4
      - name: "Create .env file"
        run: |
          touch .env
          echo HOST=${{ vars.HOST }} >> .env
          echo DBNAME=${{ vars.DBNAME }} >> .env
          echo USERNAME=${{ vars.USERNAME }} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env
          echo DBDIALECT=${{ vars.DBDIALECT }} >> .env
      - run: npm ci
      - run: npm run test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432